syntax = "proto3";

package madkv.cluster;

enum PartitioningScheme {
  PARTITIONING_SCHEME_UNSPECIFIED = 0;
  PARTITIONING_SCHEME_FNV1A_64_MOD_N = 1;
}

message ReplicaInfo {
  uint32 partition_id = 1;
  uint32 replica_id = 2;
  string address = 3;
  bool registered = 4;
}

message ClusterConfig {
  uint32 partition_count = 1;
  uint32 server_rf = 2;
  PartitioningScheme partitioning_scheme = 3;
  repeated ReplicaInfo replicas = 4;
  bool ready = 5;
}

message RegisterServerRequest {
  uint32 partition_id = 1;
  uint32 replica_id = 2;
  string address = 3;
}

message RegisterServerReply {
  ClusterConfig config = 1;
}

message GetClusterRequest {
}

message GetClusterReply {
  ClusterConfig config = 1;
}

service ClusterManager {
  rpc RegisterServer(RegisterServerRequest)
      returns (RegisterServerReply);

  rpc GetCluster(GetClusterRequest)
      returns (GetClusterReply);
}
